
pretrained: null

dataset:
  imageclef_path: /u/home/koksal/mlmi-vqa/data/external/imageclef/
  vqa_rad_path: /u/home/koksal/mlmi-vqa/data/external/VQA_RAD
  answers_list_path:
  mimic_cxr_jpg_path:
  
  split_path: /home/mlmi-matthias/Caghan/mlmi-vqa/data/external/
  num_workers: 8
  only_images: False
  limit_num_samples: null
  shuffle: True
  load_in_memory: False
  preprocessed: False
  tokenizer: gpt2


model:
  script_path: ../models/optimized.py
  pretrained_clip_path: null #/u/home/koksal/mlmi-vqa/models/PubMedCLIP_ViT32.pth
  pretrained_language_path: /u/home/koksal/mlmi-vqa/models/gpt2-pytorch_model.bin
  pretrained_model_path: 
  image_encoder: clip 
  language_encoder: gpt2
  vocab_size: 50258 
  num_tokens: 50261
  flamingo_embed_dim: 768
  depth: 12
  dim_head: 
  num_heads: 8
  att_head_dim: 64
  cross_att_every: 3
  media_token_id: 3
  perceiver_num_latents: 64
  perceicer_depth: 2
  classification_mode: True
  flamingo_mode: True
  train_embedding_layer: True
  use_positional_embedding: True
  use_image_embeddings: True
  label_smoothing: 0.1
  token_label_smoothing: 0.1
  classifier_dropout: 0.5
  #img_encoder_out_dim: 512

  # Number of Unique Answers in dataset
  num_classification_classes: 374
  return_idx_eoc: True


optimizer:
  script_path: ../optimizers/adam_keras.py
  initial_lr: 0.0001


train:
  script_path: ../train/train_keras.py
  artifacts_path: ../artifacts/cifar10_opt/
  batch_size: 64
  num_epochs: 80
  warm_up_steps: 0
  learning_rate: 0.0001
  devices: 
    - 6
  accelerator: gpu
  warmup_steps: 0
  data_augmentation:
    resize_size: [224, 224]
    horizontal_flip: 0.5
    random_rotation: 10

evaluate:
  batch_size: 1000
  augmentation_factor: 32
  data_augmentation:
    samplewise_center: False
    samplewise_std_normalization: False
    rotation_range: 0
    width_shift_range: 0.15
    height_shift_range: 0.15
    horizontal_flip: True
    vertical_flip: False
    zoom_range: 0
    shear_range: 0
    channel_shift_range: 0
    featurewise_center: False
    zca_whitening: False